# Generated by Django 5.0 on 2025-06-04 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assId', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_name', models.CharField(max_length=255, null=True)),
                ('assessment_code', models.CharField(default='None', max_length=300, null=True)),
                ('assessment_type', models.CharField(default='None', max_length=255, null=True)),
                ('assessment_discription', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, null=True)),
                ('correctanswer', models.CharField(max_length=255, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.assessment')),
            ],
        ),
    ]
