# Generated by Django 5.0 on 2025-06-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('feedback_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('assessment_name', models.CharField(max_length=300, null=True)),
                ('assessment_type', models.CharField(default='None', max_length=255, null=True)),
                ('total_accurecy', models.IntegerField(default=0, null=True)),
                ('result_generate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('ansId', models.AutoField(primary_key=True, serialize=False)),
                ('submission_id', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('assessment_name', models.CharField(max_length=300, null=True)),
                ('assessmenttype', models.CharField(max_length=300, null=True)),
                ('question_id', models.IntegerField(null=True)),
                ('video', models.FileField(blank=True, upload_to='media')),
                ('que', models.CharField(max_length=300, null=True)),
                ('c_ans', models.CharField(max_length=300, null=True)),
                ('recorded_answer', models.CharField(max_length=300, null=True)),
                ('answer_accurecy', models.IntegerField(default=0, null=True)),
                ('confidence', models.IntegerField(default=0, null=True)),
                ('nervousness', models.IntegerField(default=0, null=True)),
                ('neutral', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
